### ISSUE TITLE
Portal logout process

### ISSUE THREAD

**Issue by svenvanhal** [WISVCH/wisvch-wordpress-plugin#3]
CH Connect cannot actually logout, because:

> A browser has the login ticket in memory. As long as the ticket is not expired and the browser is not closed, the login ticket is still valid and can be used by anyone who has access to your browser.

Update the logout page to make it clear that although you've been logged out of WordPress, your credentials are still in memory.

**Comment by praseodym** [comment]
MITREid Connect 1.3.1 supports the end session endpoint, so should be possible when we upgrade (WISVCH/connect#14).
